[colors]
# General background color of the app:
background_color = [40, 40, 40]
# Login background color:
log_background_color = [40, 40, 40]
# Background color for section headers (e.g., "Continue Listening", "Library", etc.):
header_background_color = [60, 60, 60]
# Line color surrounding the header title:
line_header_color = [180, 180, 180]
# Background color of the book list:
list_background_color = [50, 50, 50]
# Background color for alternate rows of the book list:
list_background_color_alt_row = [60, 60, 60]
# Background color of the selected row of the book list:
list_selected_background_color = [80, 80, 80]
# Text color of the selected row of the book list:
list_selected_foreground_color = [180, 180, 180]
# Text and border color of the search bar:
search_bar_foreground_color = [180, 180, 180]
# Text and border color of the login section:
login_foreground_color = [180, 180, 180]
# Background color of the player:
player_background_color = [80, 80, 80]
